image: alpine

variables:
  COMMIT: ${CI_COMMIT_SHA}
  TAG: ${CI_COMMIT_REF_NAME}
  REGISTRY_REPO: registry.gitlab.com/gusisoft/onelike/notifications-service
  NOTIFICATIONS: notifications
  NOTIFICATIONS_DB: notifications-db

stages:
  - registry
  - deploy

Notifications Service:
  stage: registry
  only:
    - stage
    - master
  before_script:
    - sudo git clean -ffdx
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
    - export TAG=${CI_COMMIT_REF_NAME}_$COMMIT_TIME
    - docker login -u gitlab-ci-token -p $DOCKER_TOKEN registry.gitlab.com
    - export MAIN_REPO="https://${GITLAB_USER}:${GITLAB_PASSWORD}@gitlab.com/gusisoft/OneLike/notifications-service.git"
    - export NOTIFICATIONS_REPO="${MAIN_REPO}#${CI_COMMIT_REF_NAME}"
  script:
    - docker build $NOTIFICATIONS_REPO -t $NOTIFICATIONS:$COMMIT -f Dockerfile-${CI_COMMIT_REF_NAME}
    - docker tag $NOTIFICATIONS:$COMMIT $REGISTRY_REPO/$NOTIFICATIONS:$TAG
    - docker push $REGISTRY_REPO/$NOTIFICATIONS:$TAG
  after_script:
    - docker image rm -f $(docker images registry.gitlab.com/gusisoft/onelike/notifications-service/notifications -q)
    - sudo git clean -ffdx

Notifications DB:
  stage: registry
  only:
    - stage
  before_script:
    - sudo git clean -ffdx
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
    - export TAG=${CI_COMMIT_REF_NAME}_$COMMIT_TIME
    - docker login -u gitlab-ci-token -p $DOCKER_TOKEN registry.gitlab.com
    - export MAIN_REPO="https://${GITLAB_USER}:${GITLAB_PASSWORD}@gitlab.com/gusisoft/OneLike/notifications-service.git"
    - export NOTIFICATIONS_DB_REPO="${MAIN_REPO}#${CI_COMMIT_REF_NAME}:db"
  script:
    - docker build $NOTIFICATIONS_DB_REPO -t $NOTIFICATIONS_DB:$COMMIT -f Dockerfile
    - docker tag $NOTIFICATIONS_DB:$COMMIT $REGISTRY_REPO/$NOTIFICATIONS_DB:$TAG
    - docker push $REGISTRY_REPO/$NOTIFICATIONS_DB:$TAG
  after_script:
    - docker image rm -f $(docker images registry.gitlab.com/gusisoft/onelike/notifications-service/notifications -q)
    - sudo git clean -ffdx

Deploy Stage:
  stage: deploy
  environment:
    name: stage
    url: http://stage.onelike.gusisoft.cl
  only:
    - stage
  before_script:
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
    - export TAG=${CI_COMMIT_REF_NAME}_$COMMIT_TIME
    - rm -rf ~/.ssh
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - bash ./${CI_COMMIT_REF_NAME}-deploy.sh

Deploy Production:
  stage: deploy
  environment:
    name: production
    url: http://stage.onelike.gusisoft.cl
  only:
    - master
  before_script:
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
    - export TAG=${CI_COMMIT_REF_NAME}_$COMMIT_TIME
    - rm -rf ~/.ssh
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - bash ./${CI_COMMIT_REF_NAME}-deploy.sh
