version: '3.6'

services:
  notifications:
    container_name: notifications
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@notifications-db:5432/notifications
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 5100:5000
      - 5101:5001
