FROM node:11.6.0

RUN apt-get update && \
    apt-get -y install netcat && \
    apt-get clean

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package.json /usr/src/app/package.json
RUN npm install --silent

CMD ["/usr/src/app/entrypoint-dev.sh"]
