version: '3.6'

services:
  notifications:
    container_name: notifications
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@notifications-db:5432/notifications
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 5100:5000 # Server
      - 5101:5001 # Socket
    restart: always
    networks:
      - notifications-service-network
      - onelike-network

  notifications-db:
    container_name: notifications-db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    networks:
      - notifications-service-network

networks:
  notifications-service-network:
    name: notifications-service-network
  onelike-network:
    name: onelike-network
