version: '3.6'

services:
  notifications:
    container_name: notifications
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 5100:5000
      - 5101:5001
