openapi: "3.0.0"
info:
  title: Notifications Service
  version: 1.0.0
  description: Notifications Service API documentation
servers:
  - url: http://localhost:5100
tags:
  - name: Notifications
    description: Notifications Operations
  - name: Service Health
    description: Service Health Status
paths:
  /notifications/{hash}:
    get:
      tags:
        - Notifications
      summary: Get Notifications by hash
      description: Get Notifications by hash
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Notifications List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Notification"
        '403':
          description: Forbidden.
          content:
            application/json:
              schema:
                $ref: "#components/responses/Forbidden"
  /notifications/send:
    post:
      tags:
        - Notifications
      summary: Send Notification
      description: Send a new notification
      security:
        - bearerAuth: []
      requestBody:
        description: Notification Data
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/CreateNotification"
      responses:
        '200':
          description: Notification Send
        '403':
          description: Forbidden.
          content:
            application/json:
              schema:
                $ref: "#components/responses/Forbidden"
  /notifications/{id}:
    delete:
      tags:
        - Notifications
      summary: Delete Notification
      description: Delete a notification
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Notifications Deleted
        '403':
          description: Forbidden.
          content:
            application/json:
              schema:
                $ref: "#components/responses/Forbidden"
  /users-service/health:
    get:
      tags:
        - Service Health
      summary: Service health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Health"
components:
  schemas:
    Notification:
      properties:
        id:
          type: integer
          format: int64
          description: Notification id
        event:
          type: string
          description: Notification event
        hash:
          type: string
          description: Hash of the event
        message:
          type: object
          description: Notification body
        createdAt:
          type: string
          format: datetime
          description: Notification creation datetime
        updatedAt:
          type: string
          format: datetime
          description: Notification update datetime
    Health:
      properties:
        message:
          type: string
          description: Health status
  requestBodies:
    CreateNotification:
      required:
        - event
        - hashes
        - message
      properties:
        event:
          type: string
          description: Notification event
        hashes:
          type: array
          items:
            type: string
          description: Hashes to notify
        message:
          type: object
          description: Notification body
  responses:
    BadRequest:
      properties:
        message:
          type: string
          description: Error cause
    NotFound:
      properties:
        message:
          type: string
          description: Error cause
    Forbidden:
      properties:
        message:
          type: string
          description: Error cause

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
